/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.szinthumgui;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author diak
 */
public class MainFrame extends javax.swing.JFrame {
    ArrayList<Employee> employeeList;
    int actEmp = 0;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.employeeList = new ArrayList<>();
        initComponents();
        this.readContent();
        Employee employee = employeeList.get(0);
        this.loadEmployee(employee);
    }
    
    public void readContent()
    {
        try {
            tryreadContent();
        } catch (FileNotFoundException e) {
            System.err.println("A fájl nem található!");
        }
    }
       
    public void tryreadContent() throws FileNotFoundException
    {
        File file = new File("szinthum_dolgozok.csv");
        Scanner scanner = new Scanner(file, "utf-8");
        String firstLine = scanner.nextLine();
        while(scanner.hasNext()) 
        {
            String line = scanner.nextLine();
            // System.out.println(line);
            String[] lineArray = line.split(",");
            Employee employee = new Employee(Integer.parseInt(lineArray[0]), lineArray[1], lineArray[2], Double.parseDouble((lineArray[3])), LocalDate.parse(lineArray[4]));
            this.employeeList.add(employee);
        }
        
    }
    
    private void loadEmployee(Employee employee)
    {
        idField.setText(employee.id.toString());
        nameField.setText(employee.name);        
        cityField.setText(employee.city);
        salaryField.setText(employee.salary.toString());        
        birthdateField.setText(employee.birthdate.toString());



    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        birthdateField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        aboutButton = new javax.swing.JButton();
        storeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("Id");
        jPanel2.add(jLabel2);

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        jPanel2.add(idField);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText("Név");
        jPanel3.add(jLabel3);

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel3.add(nameField);

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setText("Település");
        jPanel4.add(jLabel4);

        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });
        jPanel4.add(cityField);

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setText("Fizetés");
        jPanel5.add(jLabel5);

        salaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryFieldActionPerformed(evt);
            }
        });
        jPanel5.add(salaryField);

        getContentPane().add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setText("Születés");
        jPanel6.add(jLabel6);

        birthdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateFieldActionPerformed(evt);
            }
        });
        jPanel6.add(birthdateField);

        getContentPane().add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        previousButton.setText("<");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        jPanel7.add(previousButton);

        nextButton.setText(">");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel7.add(nextButton);
        jPanel7.add(jLabel7);

        aboutButton.setText("Névjegy");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });
        jPanel7.add(aboutButton);

        storeButton.setText("Rögzít");
        storeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeButtonActionPerformed(evt);
            }
        });
        jPanel7.add(storeButton);

        getContentPane().add(jPanel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldActionPerformed

    private void salaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryFieldActionPerformed

    private void birthdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdateFieldActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        startNext();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        startPrevious();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void storeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeButtonActionPerformed
        startStore();
    }//GEN-LAST:event_storeButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        startAbout();
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void startAbout()
    {
        JOptionPane.showMessageDialog(this, "Juhász Roland Szoft II N");
    }
    private void startStore()
    {
        try
        {
            tryStartStore();
        }
        catch (SQLException e)
        {
            System.err.println("A beszúrás sikertelen!");            
            System.err.println(e.getMessage());

        }
    }
        
    private void tryStartStore() throws SQLException
    {
        Connection con = null;
        String url = "jdbc:mariadb://localhost:3306/szinthum";
        con = DriverManager.getConnection(url, "szinthum", "titok");
        

        Employee employee = new Employee
        (
                nameField.getText(), 
                cityField.getText(),
                Double.parseDouble(salaryField.getText()),
                LocalDate.parse(birthdateField.getText())
            
        );
        
        String sql = "insert into employees " + "(name, city, salary, birthdate) values " + "(?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, employee.name);            
        pst.setString(2, employee.city);  
        pst.setDouble(3, employee.salary);
        pst.setDate(4, java.sql.Date.valueOf(employee.birthdate));
        pst.execute();

        
    }
    
    private void startPrevious()
    {
        if(this.actEmp>0)
        {
            this.actEmp--;
            Employee employee = this.employeeList.get(this.actEmp);
            this.loadEmployee(employee);
        }
        
    }
    private void startNext()
    {
        if(this.actEmp < this.employeeList.size()-1)
        {
            this.actEmp++;
            Employee employee = this.employeeList.get(this.actEmp);
            this.loadEmployee(employee);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JTextField birthdateField;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField salaryField;
    private javax.swing.JButton storeButton;
    // End of variables declaration//GEN-END:variables
}
